name: My Github Action
on: [push]

jobs:
  publish-docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: |
    docker build -t docker.pkg.github.com/andersjanmyr/my-github-action/my-github-action:${{ github.sha }} .
    docker tag docker.pkg.github.com/andersjanmyr/my-github-action/my-github-action:${{ github.sha }} docker.pkg.github.com/andersjanmyr/my-github-action/my-github-action:latest
        docker login docker.pkg.github.com -u andersjanmyr -p $GITHUB_TOKEN
        docker push docker.pkg.github.com/andersjanmyr/my-github-action/my-github-action:${{ github.sha }}
        docker push docker.pkg.github.com/andersjanmyr/my-github-action/my-github-action:latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v1
      - uses: ./ # Uses an action in the root directory
        name: My github action
        id: hello
        with:
          who-to-greet: 'Mona the Octocat'
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"

