name: My Github Action
on: [push]

jobs:
  hello_local:
    runs-on: ubuntu-latest
    name: Hello Local Dockerfile
    steps:
      - uses: actions/checkout@v1
      - uses: ./
        name: From Dockerfile
        id: hello
        with:
          who-to-greet: 'Mona the Octocat'
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"

  publish-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: |
          docker build -t docker.pkg.github.com/andersjanmyr/my-github-action/my-github-action:${{ github.sha }} .
          docker tag docker.pkg.github.com/andersjanmyr/my-github-action/my-github-action:${{ github.sha }} docker.pkg.github.com/andersjanmyr/my-github-action/my-github-action:latest
          docker login docker.pkg.github.com -u andersjanmyr -p $GITHUB_TOKEN
          docker push docker.pkg.github.com/andersjanmyr/my-github-action/my-github-action:${{ github.sha }}
          docker push docker.pkg.github.com/andersjanmyr/my-github-action/my-github-action:latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  hello_from_docker_image:
    runs-on: ubuntu-latest
    name: from Docker Image
    steps:
      - name: From docker image
        run: |
          docker login docker.pkg.github.com -u andersjanmyr -p ${{secrets.GITHUB_TOKEN}}
          docker pull docker.pkg.github.com/andersjanmyr/my-github-action/my-github-action:latest
        id: hello
      - uses: actions/checkout@v1
      - uses: ./
        with:
          who-to-greet: 'Mona the Octocat'
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
